### PR TITLE
Initialize Express app, add dummy server, database connection, and de…

### PR DESCRIPTION
**Pull request by vinsky001**
Initialize Express app, add dummy server, database connection, and dependencies

This commit initializes an Express application, creates an entry file (index.js) with a dummy server, establishes a database connection, and installs essential project dependencies. Mongoose is added for database management, Winston for logging, and Morgan middleware for request logging.

### CODE REVIEW

**Review by SirSanctified — CHANGES_REQUESTED** [review]
The Nodejs/Express folder structure for a bigger project should take the following form, assuming you are in the `Backend` directory:

./
📂 config/
> 📋db.js

📂 controllers
>  📋 index.js

📂 middlewares

> 📋 index.js

📂 models

> 📋 index.js

📂 routes

> 📋 index.js

📂 utils

>  📋 index.js

📋 index.js
📋 README.md
📋 package.json

The `index.js` at the root is the entry file to our application.

**Comment by vinsky001** [comment]
Got it

**Comment by vinsky001** [comment]
Got it

**Review by SirSanctified — APPROVED** [review]
You can go ahead merge. Also close the issue, and move the card associated with the issue to done on the project panel

**Pull request merged**
