### PR TITLE
Added the NavBar and the Main section

### PR DESCRIPTION
**Pull request by NasheSaint**
Created the NavBar and the Hero section.
Made the NavBar to be responsive to all view sizes.
The Hero section needs attention, the mobile view is not working correctly not sure where am l going wrong with my css so can someone please have a look at the code.

### CODE REVIEW

**Review by SirSanctified — CHANGES_REQUESTED** [review]
The navbar looks good on larger devices but on smaller devices the menu bar icons are displaying at the same time. You must have missed something when conditionally rendering the open and close menu icons. Check the padding also. To close the issue associated with this pull request, you will have to implement the benefit card, and possibly add it to the landing page., then merge this pull request to automatically close the associated issue

Mock-up Mobile png

**Comment by NasheSaint** [comment]
Oky thanks, let see where did l go wrong on the navbar then also work on the benefits benefit card

**Comment by RuvimboRue** [comment]
@SirSanctified I finished the icon part. Im not quite sure what im supposed to do on the Hero section. I remember we had images of what it is supposed to look like but i cant seem to find it.

**Comment by SirSanctified** [comment]
> to

I think its just the padding that needs to be increased a little bit, otherwise it looks good. I don't know what others think. The other thing that may need a little bit adjustment is the navbar. You may consider moving it to `layout.jsx` since we'll be using it across all the pages.

**Comment by SirSanctified** [comment]
> @SirSanctified I finished the icon part. Im not quite sure what im supposed to do on the Hero section. I remember we had images of what it is supposed to look like but i cant seem to find it.

I think its just the padding that needs to be increased a little bit, otherwise it looks good. I don't know what others think. The other thing that may need a little bit adjustment is the navbar. You may consider moving it to layout.jsx since we'll be using it across all the pages.

**Review by SirSanctified — APPROVED** [review]

**Pull request merged**
